### ISSUE TITLE
Particles are cut off when page is scrolled down

### ISSUE THREAD

**Issue by oliverilm** [lindelof/particles-bg#10]
I have a problem with the particles as they are not rendered below the main screen. scrolling down, they are lost. Is there some-sort of prop that i can include or as css style that can be applied to fix that ? Thanks.

**Comment by Arcalise08** [comment]
Kind of a crude workaround to this is to go into node_modules and find the particle-bg root folder. go into index.en.js and find line

youll want to copy the node_module into your own project so that whereever you deploy it to wont download the original and overwrite the change. Oh and delete the reference to it in your package.json(with npm remove particle-bg AFTER you copy it)
```
      var style = { width: "100%", height: "100%" };
```
just change it to
```
      var style = { width: "100%", height: "200%" };
```
or like some other big number bug 200 worked for me well enough

edit: i should mention i only tested it with cobwebs and it works great. not sure about others. let me know if it doesnt work!

**Comment by lindelof** [comment]
Not sure about your specific problem. But if you want to set the particle size is very simple, you only need to set the size of the parent component.

You can refer to this demo, whether it meets the situation you said.

[https://stackblitz.com/edit/auto-size](https://stackblitz.com/edit/auto-size)

```javascript
render() {
    return (
      <>
        <div className="front"><SignIn/></div>
        <div className="swap">
          <ParticlesBg type="circle" bg={true}/>
        </div>
      </>
    );
  }
```

**Comment by Arcalise08** [comment]
> Not sure about your specific problem. But if you want to set the particle size is very simple, you only need to set the size of the parent component.
> 
> You can refer to this demo, whether it meets the situation you said.
> 
> https://stackblitz.com/edit/auto-size
> 
> ```js
> render() {
>     return (
>       <>
>         <div className="front"><SignIn/></div>
>         <div className="swap">
>           <ParticlesBg type="circle" bg={true}/>
>         </div>
>       </>
>     );
>   }
> ```

Yeah i played around with it for awhile. Its wrapped around the entire view, Yet it only generates the height of the screen. So if you have to scroll on the page at all, it will not continue generating past the height of the screen. Even the work around i provided earlier isnt really great, since height will change depending on the size of the screen viewing the page.

**Comment by lindelof** [comment]
If you have a better idea, you can submit a PR to me

**Comment by tengu-br** [comment]
Hey guys,

Commenting here in case someone is still looking for a more reliable solution. I was able to size the ParticlesBg component to match the dynamic window height by using state and effect. The main gotcha is to first make a useEffect with no depencency list (empty brackets, which makes it run only once on page load) and then have it set up the browser total height into a state, and then finally read from that state to properly size the background.

```javascript
import { useEffect, useState } from 'react'
import ParticlesBg from 'particles-bg'

export default function AnimatedBackground() {

    const [height, setHeight] = useState(0)
    
    useEffect(() => {
        setHeight(
            document.body.clientHeight)
    }, [])

    return (
        <div style={{ width: "100%", height: height, position: "absolute", zIndex: "-1", top: "0px", left: "0px" }}>
            <ParticlesBg type="polygon" num={80}  bg={true} />
        </div>
    )
}
```

The only downside is that, since the effect hook only runs on page load, if the user loads the page on a screen and then drags the window to another screen (or resizes the current one), it won't re-render. But that's a very fringe case and, at least for me, not a blocking point.
